### ISSUE TITLE
Feature : Screen sharing (double screen) - Have the choice

### ISSUE THREAD

**Issue by CodzDev** [speak/issues#142] opened 2015-08-31 15:20 UTC
### Hello,

I have a double screen and my coworker doesn't see very well my screen share because he has got a little screen. It's pretty good to have the double screen view but for the little screen's users it would be interesting to have the choice of the screen we wan't to show.

_Codzdev_

**Comment by willbarrett** [comment] 2015-08-31 15:22
Hey there - this is actually a duplicate of https://github.com/speak/issues/issues/72. We're working on it!

**Closed by willbarrett** 2015-08-31 15:22 UTC

**Comment by CodzDev** [comment] 2015-08-31 15:23
Sorry ..

**Comment by willbarrett** [comment] 2015-08-31 15:24
No worries! Thanks for the report!
