### ISSUE TITLE
Unable to quit Speak when connecting

### ISSUE THREAD

**Issue by iwaffles** [speak/issues#26] opened 2015-05-12 23:54 UTC
I was unable to quit Speak when the state was connecting. The menu bar was responding so I don't think the application was frozen.

**Comment by willbarrett** [comment] 2015-05-13 00:27
Hey @iwaffles - thanks for the report! We'll look into it!

**Comment by tommoor** [comment] 2015-05-13 17:03
@iwaffles trying to repro this. So you clicked on the menu bar icon, and "quit speak" at the bottom but nothing happened?

**Comment by iwaffles** [comment] 2015-05-13 20:12
@tommoor exactly. It seemed to have been stuck in the "Connecting" state.

**Comment by stephpalm** [comment] 2015-05-14 00:46
Having this same issue.

**Comment by willbarrett** [comment] 2015-05-14 17:41
Hey Folks - did any of you happen to move the application while it was running? We've seen some strangeness, and I think the issue here might be related...

**Comment by tommoor** [comment] 2015-05-16 00:22
We believe this and a number of other issues were caused by starting the app and then moving it out of the Downloads folder whilst it was running. We've built an installer now to avoid this in the future... restarting your Speak client should get everything fixed up.

If you do come across this again please reopen the issue - thanks for reporting!

**Closed by tommoor** 2015-05-16 00:22 UTC
Labels: bug
