### ISSUE TITLE
"Change Team" in Settings adds second Slack team to your first team

### ISSUE THREAD

**Issue by mfts** [speak/issues#103] opened 2015-06-29 17:24 UTC
I don't know if this is a bug or not. Maybe add an option to switch between Slack teams instead of adding them together. Also one user may have a different email address with a different slack team.

First two bubbles are from Team 1 and then some from Team 2, then again Team 1, and the rest from Team 2. I actually appear there twice (with a different pic; first and fourth).
![screen shot 2015-06-29 at 19 21 07](https://cloud.githubusercontent.com/assets/4049052/8413900/38d6ccbc-1e94-11e5-8e78-bb405547ecda.png)

**Comment by awsmsrc** [comment] 2015-06-29 17:50
hey @mfts thanks for the report, I think I know what the cause of this one is and will have a fix for this one tomorrow!

**Comment by awsmsrc** [comment] 2015-06-30 13:52
hey @mfts does this issue persist after a restart?

**Comment by mfts** [comment] 2015-06-30 21:53
Hi Luke, I'm rocking 0.4.4.

restart, sign in with slack and still the the same list of people (even though that slack team only has 4ppl)

I have to add that I copied the 7 character-alphanumeric invite code from the URL and just pasted it in the settings panel under "change team".

**Comment by tommoor** [comment] 2015-08-06 23:57
We're no longer offering this interface due to a lot of confusion with how this works, instead we're working on full team support and aim to get that out *very* soon.

**Closed by tommoor** 2015-08-06 23:57 UTC
Labels: bug
