### ISSUE TITLE
The dock appears in middle of screen rather than docked to the edge

### ISSUE THREAD

**Issue by laserlemon** [speak/issues#150] opened 2015-09-11 15:57 UTC
<img width="538" alt="screen shot 2015-09-11 at 11 53 49 am" src="https://cloud.githubusercontent.com/assets/34264/9819427/feb77adc-587b-11e5-9532-e11c47533200.png">

This happens when my computer wakes from sleep or when an external display is unplugged. It's _possible_ that it may also have something to do with full screen apps as I _think_ it's appeared in the middle of the screen after sleep only after swiping to a full screen app.

Hope this helps!

**Comment by tommoor** [comment] 2015-09-11 15:59
Hey Steve, thanks!

We have a fix coming for this soon, it's caused by Mac being "helpful" and moving the window into the screen because it is hidden off the side - In the meantime you can prevent this by making the dock not auto-hide if it's proving to be an annoyance :smile: 

Thanks!

**Comment by laserlemon** [comment] 2015-09-11 17:50
Cool, thank you! Might I suggest keeping this open until the bug is fixed/released? It makes it easier for others to search the issues in the meantime.

**Comment by tommoor** [comment] 2015-09-11 17:51
Yes, we'll do that!

**Comment by laserlemon** [comment] 2015-09-15 14:08
Confirmed still an issue on version 0.5.5.

**Comment by tommoor** [comment] 2015-10-05 15:58
Very happy to report that this has been fixed in todays release (0.6.0) too @laserlemon 

https://speak.io/changelog/

**Closed by tommoor** 2015-10-05 15:58 UTC
Labels: bug, fixed-in-next-release
