### ISSUE TITLE
Clicking on the tray icon should show dock when hidden

### ISSUE THREAD

**Issue by willbarrett** [speak/issues#130] opened 2015-08-19 16:04 UTC
if not in docked mode.

**Comment by awsmsrc** [comment] 2015-08-20 10:45
it totes does?

**Comment by willbarrett** [comment] 2015-08-20 12:53
This issue was reported by @laserlemon - perhaps he can share his OS version, and any more details he has? We're having some trouble replicating...

**Comment by laserlemon** [comment] 2015-08-20 13:07
<img width="698" alt="screen shot 2015-08-20 at 9 07 03 am" src="https://cloud.githubusercontent.com/assets/34264/9383960/e5a4984e-471a-11e5-9762-810c733076da.png">

**Comment by laserlemon** [comment] 2015-08-20 13:25
![speak-focus-bug](https://cloud.githubusercontent.com/assets/34264/9384266/57ce6e7a-471d-11e5-81e9-2cee6e87c4e9.gif)

**Comment by tommoor** [comment] 2015-08-27 05:21
Notice in the screencast here the shadow on the left of the screen - this is because Speak is docked and hidden. We'd need to have clicking on the dock icon unhide the dock... the problem is then that moving the mouse would immediately cause it to hide again.

ideas?

**Comment by awsmsrc** [comment] 2015-08-27 07:05
1) undock
2) unhide and let it hide when the mouse moves
3) unhide with a timeout of ten seconds, if the user is not hovering by ten seconds then re hide

**Comment by tommoor** [comment] 2015-10-05 15:56
Thanks for the report, this has been fixed in todays release (0.6.0) - see all of the details here:

https://speak.io/changelog/

**Closed by tommoor** 2015-10-05 15:56 UTC
Labels: bug, fixed-in-next-release
