### ISSUE TITLE
Slack login is failing

### ISSUE THREAD

**Issue by rnstewart** [speak/issues#24] opened 2015-05-12 19:22 UTC
I'm trying to log in with my company's Slack domain. I have successfully logged in to Slack (I have the Slack app running in the background), but when I try to log in to Speak, it just drops me back to the login screen.

**Comment by willbarrett** [comment] 2015-05-12 20:20
This was also reported by someone else on Twitter - it seems to affect a subset of users. We're looking into it. If you felt like enabling the debugging systems of the application in settings and checking the various consoles for errors, that would be super helpful!

**Comment by rnstewart** [comment] 2015-05-12 20:22
Sure, I'd be happy to help. How do I enable the debugging systems in the application?

**Comment by willbarrett** [comment] 2015-05-12 20:24
Thanks! Click on your user in the dock -> Settings, and then check the box next to 'Show debugging tomfoolery'. You will get a list of debuggers in the icon menu at the top of the screen. Click on each one to open them up, then try the login process.

**Comment by rnstewart** [comment] 2015-05-12 20:25
I can't do that. Preferences is disabled in the dock menu.

**Comment by sdhull** [comment] 2015-05-12 23:40
This is happening to me as well.

I created a different login so I could enable debugging in preferences.

I observed the debugger windows while trying to login, but nothing interesting happened. What exactly are you looking for?

**Comment by tommoor** [comment] 2015-05-12 23:45
We've just had this reported by someone who only has permissions to view a single channel in the slack org they are trying to signin to. @sdhull @rnstewart are either of you aware of having restricted permissions on your slack account?

**Comment by sdhull** [comment] 2015-05-13 02:42
No I'm pretty sure I have full permissions on my slack org.

But it's possible other aspects of our slack setup is weird... the thing is
it worked fine for my colleague. So it's probably not a problem with our
slack org itself...

-S

**Comment by rnstewart** [comment] 2015-05-13 17:04
AFAIK, I have full permissions on my Slack org as well. Not sure if this is relevant, but I noticed that the dock menu for Speak says "connecting..." at the top. It looks like it's having trouble connecting to the servers.

**Comment by tommoor** [comment] 2015-05-13 18:37
@rnstewart @sdhull one more question, did either of you sign up with email prior to signing up with Slack? thanks!

**Comment by rnstewart** [comment] 2015-05-13 18:38
No, I didn't. The first time I signed in was with my Slack org.

**Comment by katiemccann** [comment] 2015-05-13 22:50
Having this issue as well - I have access to the vast majority of our org's Slack channels, but probably not full access.  (And no, I didn't sign up with an email first either- logging in with Slack is my first attempt to use the app)

**Comment by tommoor** [comment] 2015-05-14 21:08
Hey all, we just released a new version which includes better handling of Slack authentication errors. We should be able to figure out what's going wrong here if you give updating the app a try :smile: 

Thanks so much!

**Comment by rnstewart** [comment] 2015-05-14 21:41
Thanks for your work on this! I downloaded the latest version (0.3.0, right?), and tried again, but it fails in the same way. Is there anything I can do to get you guys more information?

**Comment by tommoor** [comment] 2015-05-14 21:50
@rnstewart YES! If you open console.app try the signup and take a screenshot of the contents of console.app it might offer us some clues as to the events that are being triggered

**Comment by sdhull** [comment] 2015-05-14 23:04
This doesn't strike me as useful...
```
5/14/15 4:02:00.343 PM Speak[96863]: window.focus { id: 1 }
5/14/15 4:02:22.412 PM Speak[96863]: app.show signin
5/14/15 4:02:26.814 PM Speak[96863]: window.blur { id: 1 }
5/14/15 4:02:53.503 PM Speak[96863]: app.show signin
5/14/15 4:02:53.633 PM Speak[96863]: window.focus { id: 1 }
5/14/15 4:02:55.505 PM Speak[96863]: app.show signup-with-slack
5/14/15 4:03:07.988 PM Speak[96863]: app.show signup
5/14/15 4:03:11.776 PM Speak[96863]: window.blur { id: 1 }
```

**Comment by tommoor** [comment] 2015-05-14 23:22
@rnstewart @sdhull you're right, not terribly :( if one of you would be kind enough to jump on a quick screenshare with me I could probably live debug in 10mins or so... email tom@speak.io and we'll set something up :smile:

**Comment by tommoor** [comment] 2015-05-15 18:08
Hey everyone, it looks like this issue is caused by not having a profile picture in Slack. We'll be releasing a new version of the app that accounts for this eventuality but if you'd like to get access today simply upload a picture like so:

![image](https://cloud.githubusercontent.com/assets/380914/7658849/a0f76376-faf2-11e4-9a4a-b5ff9c03ed25.png)

You should be able to signup fine then :smile:

**Comment by rnstewart** [comment] 2015-05-15 18:09
Can confirm this fix worked for me. Also, if Speak can't sign in after you update your profile picture, try quitting Slack and starting it again.

**Comment by sdhull** [comment] 2015-05-15 18:14
I definitely have had a profile picture in slack since day 1...

-S

**Comment by tommoor** [comment] 2015-05-15 18:19
@sdhull oakies. I'm going to send you a link to a custom build shortly, thanks for your patience

**Comment by katiemccann** [comment] 2015-05-15 21:13
Adding a profile pic to my Slack solved it for me (no updated build needed)

**Comment by tommoor** [comment] 2015-05-15 21:14
@katiemccann great! :dancers: 

Thanks for letting us know

**Comment by sdhull** [comment] 2015-05-16 00:11
FYI my issue was caused by domain identity crises.

I originally signed up with one domain, but then my team turned on Google Account SSO (where I have a legacy email domain), so slack wanted me to "setup my new account" with my new email address.

So got it all ironed out, had my admin send my _old_ email address an "SSO binding email" so now it's magically working.

**Comment by tommoor** [comment] 2015-05-18 19:49
The two issues here have now been addressed in the latest builds. Thanks for your help everyone :smile:

**Closed by tommoor** 2015-05-18 19:49 UTC
Labels: bug, in-progress
